### PR TITLE
Honor creation timestamp for signatures again

### LINKED ISSUE #3298: OCI manifest created timestamp wrong with v2.2.0
**Description**

We are using a cosign container inside our pipeline to sign newly build images. 
Up until v2.1.1 (public.ecr.aws/bitnami/cosign:2.1.1) this works without problems:
`cosign sign --yes --key cosign.key {{image}}@sha256:{{digest}}`
That creates a new OCI entry inside our IBM Container Registry:
```json
{
  "Id": "sha256:[...]",
  "Parent": "",
  "Comment": "",
  "Created": "2023-10-12T14:52:17.989015938Z",
[...]
  "Size": 251,
  "VirtualSize": 251,
  "RootFS": {
    "Type": "layers",
    "Layers": [
      "sha256:[...]"
    ]
  },
  "ManifestType": "application/vnd.oci.image.manifest.v1+json"
}
```
After updating to v2.2.0 (public.ecr.aws/bitnami/cosign:2.2.0) the **Created** timestamp is totally wrong and leads to this:
```json
{
  "Id": "sha256:[...]",
  "Parent": "",
  "Comment": "",
  "Created": "0001-01-01T00:00:00Z",
 [...]
  "Size": 251,
  "VirtualSize": 251,
  "RootFS": {
    "Type": "layers",
    "Layers": [
      "sha256:[...]"
    ]
  },
  "ManifestType": "application/vnd.oci.image.manifest.v1+json"
}
```

As we have some rules to delete older entries inside our registry these signatures are deleted soon after creation.
Image can be verified with `cosign verify` in both cases. The output does not differ.
This can be reproduced with different images.

**Version**

`public.ecr.aws/bitnami/cosign:2.2.0`

### PR DESCRIPTION
**Pull request by Lerentis**
closes #3298

#### Summary

As the timestamp is part of the OCI spec it makes no sense to omit it. signatures that are pushed to an OCI registry are not immutable by default and honoring the creation timestamp will enable people to use time based cleanup policies in their registries again (as in GCP, GitLab etc.).

#### Release Note

Fixes null timestamp in signatures and honor creation timestamp again

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
lgtm

**Comment by haydentherapper** [comment]
@jonjohnsonjr  can you chime in on this, as you made the change originally?

**Comment by bobcallaway** [comment]
Also @imjasonh to comment

**Comment by haydentherapper** [comment]
Bumping, @imjasonh @jonjohnsonjr did you have thoughts on this?

**Comment by bobcallaway** [comment]
Can we leave the behavior currently implemented as the default, and add a feature flag to correctly set the timestamp?

**Comment by Lerentis** [comment]
> Can we leave the behavior currently implemented as the default, and add a feature flag to correctly set the timestamp?

@bobcallaway  I hope i got every reference where this would make sense. please double check this as the codebase is not that common to me

File: cmd/cosign/cli/options/sign.go [hunk 1]
```diff
@@ -130,4 +131,6 @@ func (o *SignOptions) AddFlags(cmd *cobra.Command) {
 
 	cmd.Flags().StringVar(&o.SignContainerIdentity, "sign-container-identity", "",
 		"manually set the .critical.docker-reference field for the signed identity, which is useful when image proxies are being used where the pull reference should match the signature")
+
+	cmd.Flags().BoolVar(&o.HonorCreateTimestamp, "honor-create-timestamp", false, "honor the create timestamp in the signature artefact to be pushed to the OCI registry")
```
Comment (bobcallaway) [inline cmd/cosign/cli/options/sign.go:135]:
```suggestion
	cmd.Flags().BoolVar(&o.RecordCreationTimestamp, "record-creation-timestamp", false, "set the createdAt timestamp in the signature artifact to the time it was created; by default, cosign sets this to the zero value")
```

Code looks fine otherwise.

Comment (Lerentis) [reply cmd/cosign/cli/options/sign.go]: changed as requested and unified variable naming :+1:

**Comment by Lerentis** [comment]
> /opt/hostedtoolcache/go/1.21.8/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device

the ci failure seems like an infra issue?

**Comment by bobcallaway** [comment]
> > /opt/hostedtoolcache/go/1.21.8/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
> 
> the ci failure seems like an infra issue?

yes, I'm working to unblock this now.

**Comment by bobcallaway** [comment]
> > > /opt/hostedtoolcache/go/1.21.8/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
> > 
> > 
> > the ci failure seems like an infra issue?
> 
> yes, I'm working to unblock this now.

can you rebase this please? I think the infra issue is fixed now.

**Comment by Lerentis** [comment]
> > > > /opt/hostedtoolcache/go/1.21.8/x64/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
> > > 
> > > 
> > > the ci failure seems like an infra issue?
> > 
> > 
> > yes, I'm working to unblock this now.
> 
> can you rebase this please? I think the infra issue is fixed now.

all green now. thanks for taking care of this :tada:

File: cmd/cosign/cli/sign.go [hunk 2]
```diff
@@ -83,7 +83,10 @@ race conditions or (worse) malicious tampering.
   cosign sign --key cosign.key --tlog-upload=false <IMAGE DIGEST>
 
   # sign a container image by manually setting the container image identity
-  cosign sign --sign-container-identity <NEW IMAGE DIGEST> <IMAGE DIGEST>`,
+  cosign sign --sign-container-identity <NEW IMAGE DIGEST> <IMAGE DIGEST>
+
+  # sign a container image and honor the creation timestamp of the signature
+  cosign sign --key cosign.key --honor-create-timestamp <IMAGE DIGEST>`,
```
Comment (bobcallaway) [inline cmd/cosign/cli/sign.go:89]:
```suggestion
  # sign a container image and honor the creation timestamp of the signature
  cosign sign --key cosign.key --record-creation-timestamp <IMAGE DIGEST>`,
```

File: pkg/oci/mutate/options.go [hunk 3]
```diff
@@ -59,6 +60,12 @@ func WithReplaceOp(ro ReplaceOp) SignOption {
 	}
 }
 
+func WithHonorCreationTimestamp(rct bool) SignOption {
```
Comment (bobcallaway) [inline pkg/oci/mutate/options.go:63]:
```suggestion
func WithRecordCreationTimestamp(rct bool) SignOption {
```

File: cmd/cosign/cli/sign/sign.go [hunk 4]
```diff
@@ -329,7 +329,7 @@ func signDigest(ctx context.Context, digest name.Digest, payload []byte, ko opti
 	}
 
 	// Attach the signature to the entity.
-	newSE, err := mutate.AttachSignatureToEntity(se, ociSig, mutate.WithDupeDetector(dd))
+	newSE, err := mutate.AttachSignatureToEntity(se, ociSig, mutate.WithDupeDetector(dd), mutate.WithHonorCreationTimestamp(signOpts.RecordCreationTimestamp))
```
Comment (bobcallaway) [inline cmd/cosign/cli/sign/sign.go:332]:
```suggestion
	newSE, err := mutate.AttachSignatureToEntity(se, ociSig, mutate.WithDupeDetector(dd), mutate.WithRecordCreationTimestamp(signOpts.RecordCreationTimestamp))
```

**Review by bobcallaway — COMMENTED** [review]
a couple nits but otherwise LGTM and will merge once fixed.

**Comment by Lerentis** [comment]
> a couple nits but otherwise LGTM and will merge once fixed.

changed as requested :+1:

**Review by bobcallaway — APPROVED** [review]
