### PR TITLE
Verify ignore scratch images

### LINKED ISSUE #508: verify-dockerfile  Does not appropriately handle scratch images.
**Description**

`cosign verify-dockerfile -key $key Dockerfile` Does not appropriately handle scratch images.

```
error: GET https://index.docker.io/v2/library/scratch/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; map[Tag:latest]
```

### PR DESCRIPTION
**Pull request by rjbrown57**
Fixes #508

### CODE REVIEW

File: cmd/cosign/cli/verify.go [hunk 1]
```diff
@@ -146,6 +146,12 @@ func (c *VerifyCommand) Exec(ctx context.Context, args []string) (err error) {
 	co.SigVerifier = pubKey
 
 	for _, imageRef := range args {
+
+		if imageRef == "scratch" {
```
Comment (dlorenc) [inline cmd/cosign/cli/verify.go:150]: Should we normalize the case here on imageRef to support SCRATCH? or is that handled somewhere else too

Comment (rjbrown57) [reply cmd/cosign/cli/verify.go:150]: I think it's unnecessary. A test with a `FROM SCRATCH` Dockerfile shows repositories must be lowercase.

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "SCRATCH": invalid reference format: repository name must be lowercase 
```

**Comment by dekkagaijin** [comment]
Is there a use-case where "scratch" is being verified directly with `verify`? Or is meant to fix an issue with `verify-dockerfile`? If the latter, it'd be better to patch that command. FWIW I thought I had already special-cased `FROM scratch` in `verify-dockerfile` but I was clearly mistaken

**Comment by rjbrown57** [comment]
> Is there a use-case where "scratch" is being verified directly with `verify`? Or is meant to fix an issue with `verify-dockerfile`? If the latter, it'd be better to patch that command. FWIW I thought I had already special-cased `FROM scratch` in `verify-dockerfile` but I was clearly mistaken

At least when a user is running with docker and "scratch" defaults to "https://index.docker.io/v2/library/scratch" I don't think anyone will run verify scratch.

Would it make more sense to filter somewhere in https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify_dockerfile.go#L115?

**Comment by rjbrown57** [comment]
Updated to ignore scratch in verify-dockerfile

**Review by dlorenc — APPROVED** [review]
