### PR TITLE
fixing issue 3426

### LINKED ISSUE #3426: Release 2.2.2 break BYO PKI verification (trying to fetching CT Log Public key when it is not needed/available)
**Description**
Code change done under Issue 3415 has introduce a piece of code to fetch CT Log Public key even  if user is providing --insecure-ignore-sct=true. Now in impacts the following use case.

Signer has a Local Instance of PKI and is using a Air gaped environment to  generate signatures, so this means we can no use public instance of TUF, Rekor etc.
The Signer shares the signature and associated certificates and cert chain to its clients. the client have the Trusted root certificate from Signer to verify the signatures.
Now when verifier uses the Root Cert to verify the signature with the new code change cosign is trying to get the CT Log Public Key. Which is not needed in this use case and due to this verification fails.

**Version** : 2.2.2.

This code change has impacted BYO PKI case.
We are using our company PKI to generate signatures and attach those in registry. We pass the Root certificate to the Verifier and using the root certificate we are able to verify the Certificate chain -> Leaf cert -> Signature,
We dont use any of the Tlog and SCT feature as our server are working mostly in an Airgap mode no connection to external internet servers.

So the problem is that even we are passing the flags like "--insecure-ignore-sct=true --insecure-ignore-tlog=true" still cosign is trying to fetch the ctlog public key for verification which we dont want to use.

cosign verify harbor.demo-ncd.services.te0014-demo-ncd.dyn.nesc.net/ncd-orb/orbs/ncd-ncd_fp6_generic-799@sha256:c08f847db8877aeefa3852ae9ee471fa7c421be4089b855fd0e545d521e2d87c --certificate-identity-regexp='.' --certificate-oidc-issuer-regexp='.' --insecure-ignore-sct=true --insecure-ignore-tlog=true --cert-chain=rootCA.crt --verbose=true
WARNING: Skipping tlog verification is an insecure practice that lacks of transparency and auditability verification for the signature.
Error: getting ctlog public keys: updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get https://tuf-repo-cdn.sigstore.dev/8.root.json: dial tcp 34.117.62.14:443: i/o timeout
remote status:{
"mirror": https://tuf-repo-cdn.sigstore.dev/,
"metadata": {}
}
main.go:74: error during command execution: getting ctlog public keys: updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get https://tuf-repo-cdn.sigstore.dev/8.root.json: dial tcp 34.117.62.14:443: i/o timeout
remote status:{
"mirror": https://tuf-repo-cdn.sigstore.dev/,
"metadata": {}
}

The same result, if I provide the rootCA.crt file as an env variable:

export SIGSTORE_ROOT_FILE=/home/sanyi/cosign-2/rootCA.crt
cosign verify harbor.demo-ncd.services.te0014-demo-ncd.dyn.nesc.net/ncd-orb/orbs/ncd-ncd_fp6_generic-799@sha256:c08f847db8877aeefa3852ae9ee471fa7c421be4089b855fd0e545d521e2d87c --certificate-identity-regexp='.' --certificate-oidc-issuer-regexp='.' --insecure-ignore-tlog=true --insecure-ignore-sct=true --verbose=true
WARNING: Skipping tlog verification is an insecure practice that lacks of transparency and auditability verification for the signature.
Error: getting ctlog public keys: updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get https://tuf-repo-cdn.sigstore.dev/8.root.json: dial tcp 34.117.62.14:443: i/o timeout
remote status:{
"mirror": https://tuf-repo-cdn.sigstore.dev/,
"metadata": {}
}
main.go:74: error during command execution: getting ctlog public keys: updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get https://tuf-repo-cdn.sigstore.dev/8.root.json: dial tcp 34.117.62.14:443: i/o timeout
remote status:{
"mirror": https://tuf-repo-cdn.sigstore.dev/,
"metadata": {}
}

The code change done

https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify/verify.go (209):
// Ignore Signed Certificate Timestamp if the flag is set or a key is provided
if !c.IgnoreSCT || keylessVerification(c.KeyRef, c.Sk) {
co.CTLogPubKeys, err = cosign.GetCTLogPubs(ctx)
if err != nil {
return fmt.Errorf("getting ctlog public keys: %w", err)
}
}

goes into the section to get CT Log Key if IgnoreSCT is false or the keylessVerification function return True.
As in my case i am using Keyless functionality for verify and dont want to use SCT but due to this cosign is still trying to fetch the ctlog public key, this has broken the existing running functionality for BYO PKI.

I propose to enhance this check to also see if user is not passing any CertChain in verify command else we should not go for CTLog Public Key if use is asked for ignore SCT.

### PR DESCRIPTION
**Pull request by Mukuls77**
Closes #3426 

#### Summary
The PR fixes the issue mentioned in issue #3426 
The code changes done in this PR allow user to do cosign verification for a BYO PKI use case. 
The use case is that it is a restricted environment, i.e. no access to TUF root CDN.
Signer has a BYO PKI which generates signatures, and attach those to registry.
Verifier uses Trusted root certificate shared by signer to to verification in a Air gap environment with no access to TUF root CDN. 
The user passes the flags
cosign verify harbor.demo-ncd.services.te0014-demo-ncd.dyn.nesc.net/ncd-orb/orbs/ncd-ncd_fp6_generic-799@sha256:c08f847db8877aeefa3852ae9ee471fa7c421be4089b855fd0e545d521e2d87c --certificate-identity-regexp='.*' --certificate-oidc-issuer-regexp='.*' --insecure-ignore-sct=true --insecure-ignore-tlog=true --cert-chain=rootCA.crt --verbose=true

so user has provided --insecure-ignore-sct=true but still cosign verification was failing. due to code changes done in PR
https://github.com/sigstore/cosign/pull/3415

which has introduced the code change
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/verify/verify.go (209):
// Ignore Signed Certificate Timestamp if the flag is set or a key is provided
     if !c.IgnoreSCT || keylessVerification(c.KeyRef, c.Sk) {
           co.CTLogPubKeys, err = cosign.GetCTLogPubs(ctx)
           if err != nil {
                return fmt.Errorf("getting ctlog public keys: %w", err)
           }
     }

With this code change the passing of flag IgnoreSCT  was not of much use in keylessverification as it was still going to get CTLogPub key from CND TUF, so this impact the BYO PKI use case where we are using keyless verification by passing Trusted Root certificate via --cert-chain argument or using SIGSTORE_ROOT_FILE env variable.
The code changes done in this PR introduces following logic
1. if user provide key we dont need to pass --insecure-ignore-sct=true 
2. If user is using keyless verification using cert-chain or SIGSTORE_ROOT_FILE option and passing --insecure-ignore-sct=true than cosign will not go to get CTLog Public key.

#### Release Note
Fixes Issue #3426 
File changed:
/cosign/cmd/cosign/cli/verify/verify.go
/cosign/cmd/cosign/cli/verify/verify_attestation.go
/cosign/cmd/cosign/cli/verify/verify_blob.go
/cosign/cmd/cosign/cli/verify/verify_blob_attestation.go

Introduced a new function to check if it is keylessverification using SCT option.
func keylessVerificationWithSCTEnabled(IgnoreSCT bool, keyRef string, sk bool, CertChain string) bool {
        rootEnv := env.Getenv(env.VariableSigstoreRootFile)
        if keyRef != "" {
                return false
        }
        if sk {
                return false
        }
        if IgnoreSCT && (CertChain != "" || rootEnv != "") {
                return false
        }
        if IgnoreSCT {
                return false
        }
        return true
}

and used this function to check if we need to get CTLogs Public key or not during Verify signature procedure.

#### Documentation
No change is needed in Documentation

### CODE REVIEW

File: cmd/cosign/cli/verify/verify.go [hunk 1]
```diff
@@ -500,3 +501,20 @@ func keylessVerification(keyRef string, sk bool) bool {
...
+
+func keylessVerificationWithSCTEnabled(ignoreSCT bool, keyRef string, sk bool, certChain string) bool {
+	rootEnv := env.Getenv(env.VariableSigstoreRootFile)
+	if keyRef != "" {
+		return false
+	}
+	if sk {
+		return false
+	}
+	if ignoreSCT && (certChain != "" || rootEnv != "") {
```
Comment (haydentherapper) [inline cmd/cosign/cli/verify/verify.go:513]: This logic can be simplified, you can remove this conditional since only the value of `ignoreSCT` matters.

File: cmd/cosign/cli/verify/verify.go [hunk 2]
```diff
@@ -500,3 +501,20 @@ func keylessVerification(keyRef string, sk bool) bool {
 	}
 	return true
 }
+
+func keylessVerificationWithSCTEnabled(ignoreSCT bool, keyRef string, sk bool, certChain string) bool {
```
Comment (haydentherapper) [inline cmd/cosign/cli/verify/verify.go:505]: Can you rename this to `shouldVerifySCT`? Clearer what its purpose is.

File: cmd/cosign/cli/verify/verify.go [hunk 3]
```diff
@@ -207,7 +208,7 @@ func (c *VerifyCommand) Exec(ctx context.Context, images []string) (err error) {
 	certRef := c.CertRef
 
 	// Ignore Signed Certificate Timestamp if the flag is set or a key is provided
-	if !c.IgnoreSCT || keylessVerification(c.KeyRef, c.Sk) {
```
Comment (haydentherapper) [inline cmd/cosign/cli/verify/verify.go:210]: Whoops, lack of good unit tests and boolean logic caused this!

**Review by haydentherapper — CHANGES_REQUESTED** [review]

File: cmd/cosign/cli/verify/verify.go (hunk 2 above)
Comment (Mukuls77) [reply cmd/cosign/cli/verify/verify.go:505]: Agree i will change the name of function to shouldVerifySCT(ignoreSCT bool, keyRef string, sk bool)

File: cmd/cosign/cli/verify/verify.go (hunk 1 above)
Comment (Mukuls77) [reply cmd/cosign/cli/verify/verify.go:513]: Agree i will remove the condition check for certChian and root ENV will check only for ignoreSCT in the mentioned condition.

**Comment by Mukuls77** [comment]
@haydentherapper  i have done the requested changes pls review

**Review by hectorj2f — DISMISSED** [review]
~keylessVerification doesn't seem to be used anywhere else. So we could remove this function now.~

**Comment by Mukuls77** [comment]
> keylessVerification doesn't seem to be used anywhere else. So we could remove this function now.

@hectorj2f   keylessVerification function is still used in other places
/c/Users/musharma/cosign>grep -R "keylessVerification"
cmd/cosign/cli/verify/verify.go:        if keylessVerification(c.KeyRef, c.Sk) {
cmd/cosign/cli/verify/verify.go:func keylessVerification(keyRef string, sk bool) bool {
cmd/cosign/cli/verify/verify_attestation.go:    if keylessVerification(c.KeyRef, c.Sk) {
cmd/cosign/cli/verify/verify_blob.go:   if keylessVerification(c.KeyRef, c.Sk) {
cmd/cosign/cli/verify/verify_blob_attestation.go:       if keylessVerification(c.KeyRef, c.Sk) {

so removing that will require changes in all these files.

**Review by haydentherapper — APPROVED** [review]
