### PR TITLE
fix: make isTerminal suitable for windows

### LINKED ISSUE #862: Password input from terminal in Windows do not work
## Issue description
When launched, the application freezes and does not prompt user for a password. 
This happens whenever entering password is expected from the user. For example these commands:

`cosign generate-key-pair`
`cosign sign --key cosign.key ...`

It works just fine when password is passed from stdin or from COSIGN_PASSWORD environment variable.

It seems that this is caused by golang.org/x/term module that is [being used](https://github.com/sigstore/cosign/blob/d49fa5473c37afa192daf31cf48ae7f57bad3377/cmd/cosign/cli/generate/generate_key_pair.go#L100) to read password from terminal, but this module does not support Windows. See module description:

"Package term provides support functions for dealing with terminals, as commonly found on UNIX systems. "

## My environment
- Windows 11 (21H2 - build 22000.194), Windows 10 (21H1 - build 19043.1237)
- cosign v1.2.1
- Windows Terminal 1.10.2714.0, native cmd.exe

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

#### Summary

make isTerminal suitable for windows

#### Ticket Link

Fixes #862 

#### Release Note

```release-note
* Fix make isTerminal suitable for windows
```

### CODE REVIEW

File: cmd/cosign/cli/generate/generate_key_pair.go [hunk 1]
```diff
@@ -116,6 +116,15 @@ func readPasswordFn(confirm bool) func() ([]byte, error) {
 	}
 }
 
+func isTerminal() bool {
+	stat, _ := os.Stdin.Stat()
+	if (stat.Mode() & os.ModeCharDevice) == 0 {
+		return false
+	} else {
+		return true
```
Comment (dekkagaijin) [inline cmd/cosign/cli/generate/generate_key_pair.go:124]:
```suggestion
	return (stat.Mode() & os.ModeCharDevice) != 0
```

**Review by dekkagaijin — APPROVED** [review]
