### PR TITLE
Route deprecated  -version to version subcommand

### LINKED ISSUE #1811: 'cosign -version' tells me to use 'cosign --version'
cosign version 1.8.0 outputs a misleading warning when used with the `-version` flag:
```
imre@silicon:~$ cosign -version
WARNING: the flag -version is deprecated and will be removed in a future release. Please use the flag --version.
[..]
```

This is not helpful as the `--version` flag doesn't work either:
```
imre@silicon:~$ cosign --version
Error: unknown flag: --version
main.go:52: error during command execution: unknown flag: --version
```

In fact, there is no version *flag* at all. The user should be told to use the version *command* instead:
```
imre@silicon:~$ cosign version
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v1.8.0
GitCommit:     9ef6b207218572b3257a5b4251418d75569baaae
GitTreeState:  clean
BuildDate:     2022-04-27T13:40:34Z
GoVersion:     go1.17.9
Compiler:      gc
Platform:      linux/amd64
```

### PR DESCRIPTION
**Pull request by puerco**
#### Summary

This commit fixes the routing of the deprecated -version flag to avoid translating it to --version. Instead, it routes the flag to the `version` subcommand, prefixing it with the deprecation warning.

Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>

#### Ticket Link

Fixes https://github.com/sigstore/cosign/issues/1811

#### Release Note
```release-note
The -version flag now works as other deprecated flags, patching it to the expected output and preceding it with a warning
```

### CODE REVIEW

File: cmd/cosign/main.go [hunk 1]
```diff
@@ -43,6 +43,9 @@ func main() {
 		} else if strings.HasPrefix(arg, "-") {
 			// Handle -output, convert to --output
 			newArg := fmt.Sprintf("-%s", arg)
+			if newArg == "--version" {
+				newArg = "version"
```
Comment (cpanato) [inline cmd/cosign/main.go:47]: sounds good, but the message that outputs is not correct, maybe we can change the message for this case?
because it says

````
$ ./cosign -version
WARNING: the flag -version is deprecated and will be removed in a future release. Please use the flag version.
```

is to use the `command` and not the `flag`

**Review by hectorj2f — APPROVED** [review]
